<?php
	session_start();
	require_once('../config.php');
	require('../fpdf.php');
	require_once('../function.php');
 	require_once('../function-cashier.php');
	class REPORTS extends FPDF
	{
		function setReportName($rname)
		{
			$this->reportname = $rname;
		}

		function setFooter($flag)
		{
			$this->setFlag = $flag;
		}

		function setDate($daterel)
		{
			$this->datereleased = $daterel;
		}

		function setRelNum($rel)
		{
			$this->relnum = $rel;
		}

		function setFooterText($text)
		{
			$this->footertext = $text;
		}

		function Footer()
		{
			if($this->setFlag)
			{
				$this->SetY(-15);
				$this->SetTextColor(74, 74, 74);
				$this->SetFont("Arial", "", 7);
				// $this->SetDrawColor(74, 74, 74);
				// $this->SetLineWidth(0.2);
				// $this->Line(10, 265, 205, 265);
				$this->Cell(0, 10, "Page ".$this->PageNo()." - {nb}", 0, 0, "C");
				$this->Cell(0, 10, $this->footertext, 0, 0, "R");				
			}

		}

		function docHeader($link)
		{
			// get user department
			$this->SetFont("Helvetica", "B", 12);
			$this->SetTextColor(28, 28, 28);
			$this->Cell(0, 8, 'ALTURAS GROUP OF COMPANIES', 0, 0, "C");			
			$this->Ln(6);
			$this->SetFont("times", "B",11);
			$this->SetTextColor(28, 28, 28);
			$this->Cell(0, 8, strtoupper(getStoreName($link,$_SESSION['gc_store'])), 0, 0, "C");
			$this->Ln(1);
			$this->SetFont("times", "B",11);
			$this->SetTextColor(28, 28, 28);
			$this->Ln();
			$this->Cell(0, 1, $this->reportname, 0, 0, "C");	
			$this->Ln(10);
		}

		function docHeaderReport($link,$d1,$d2)
		{
			// get user department
			$this->SetFont("Helvetica", "B", 12);
			$this->SetTextColor(28, 28, 28);
			$this->Cell(0, 8, 'ALTURAS GROUP OF COMPANIES', 0, 0, "C");			
			$this->Ln(6);
			$this->SetFont("times", "B",11);
			$this->SetTextColor(28, 28, 28);
			$this->Cell(0, 6, strtoupper(getStoreName($link,$_SESSION['gc_store'])), 0, 0, "C");
			$this->Ln();
			$this->SetFont("times", "B",11);
			$this->SetTextColor(28, 28, 28);
			$this->Cell(0, 5, $this->reportname, 0, 0, "C");	
			$this->Ln();
			if($d1 == $d2)
			{
				$this->Cell(0, 5,_dateFormat($d1), 0, 0, "C");
			}
			else 
			{
				$this->Cell(0, 5,'From '._dateFormat($d1).' to '._dateFormat($d2), 0, 0, "C");
			}
			$this->Ln(2);
		}

		function subheaderVerification($todays_date)
		{
			$this->SetFont("Arial", "B", 10);
			$this->Cell(28,5,'Generated By:',0,0,'R');
			$this->SetFont("Arial", "", 10);
			$this->Cell(86,5,ucwords($_SESSION['gc_fullname']),0,0,'L');
			$this->SetFont("Arial", "B", 10);
			$this->Cell(40,5,'Date Printed:',0,0,'R');
			$this->SetFont("Arial", "", 10);
			$this->Cell(50,5,_dateFormat($todays_date),0,0,'L');
			$this->Ln(10);
		}

		function displayVerifiedGCByRange($link,$d1,$d2,$storeid)
		{
			$this->Cell(0, 8, 'Verified GC', 0, 0, "L");
			$this->Ln();
			if($d1==$d2)
			{
				$table = 'store_verification';
				$select = "store_verification.vs_barcode,
				    CONCAT(customers.cus_fname,' ',customers.cus_lname) as customer,
				    CONCAT(users.firstname,' ',users.lastname) as verby,
				    store_verification.vs_tf_denomination,
				    store_verification.vs_tf_used,
				    store_verification.vs_gctype,
				    store_verification.vs_date,
				    store_verification.vs_reverifydate,
				    store_verification.vs_tf_balance";
				$where = "DATE_FORMAT(store_verification.vs_date,'%Y-%m-%d') = '".$d1."' 
					AND 
						store_verification.vs_store='".$storeid."'";
				$join = 'LEFT JOIN
						customers
					ON
						customers.cus_id = store_verification.vs_cn
					LEFT JOIN
						users
					ON
						users.user_id = store_verification.vs_by';
				$limit = '';
				$data = getAllData($link,$table,$select,$where,$join,$limit);
			}
			else
			{
				$table = 'store_verification';
				$select = "store_verification.vs_barcode,
				    CONCAT(customers.cus_fname,' ',customers.cus_lname) as customer,
				    CONCAT(users.firstname,' ',users.lastname) as verby,
				    store_verification.vs_tf_denomination,
				    store_verification.vs_tf_used,
				    store_verification.vs_gctype,
				    store_verification.vs_date,
				    store_verification.vs_reverifydate,
				    store_verification.vs_tf_balance";
				$where = "DATE_FORMAT(store_verification.vs_date,'%Y-%m-%d') >= '".$d1."'
					AND
						DATE_FORMAT(store_verification.vs_date,'%Y-%m-%d') <='".$d2."'
					AND
						store_verification.vs_store='".$storeid."'";
				$join = 'LEFT JOIN
						customers
					ON
						customers.cus_id = store_verification.vs_cn
					LEFT JOIN
						users
					ON
						users.user_id = store_verification.vs_by';
				$limit = '';
				$data = getAllData($link,$table,$select,$where,$join,$limit);

			}

			if(count($data) > 0)
			{
				$this->SetFont("Arial", "B", 9);
				$this->Cell(1,5,'',0,0,'R');
				$this->Cell(26,5,'Barcode #',1,0,'L');
				$this->Cell(24,5,'Denomination',1,0,'L');
				$this->Cell(27,5,'GC Type',1,0,'L');
				$this->Cell(40,5,'Customer',1,0,'L');
				$this->Cell(20,5,'Status',1,0,'L');
				$this->Cell(24,5,'Balance',1,0,'L');
				$this->Cell(24,5,'Date',1,0,'L');
				$this->Ln();				
				foreach ($data as $d) 
				{
					$balance = "";
					$gctype="";
					$gcstatus = "";
					$customername = "";
					$this->Cell(1,5,'',0,0,'R');
					$this->Cell(26,5,$d->vs_barcode,1,0,'L');
					$this->Cell(24,5,number_format($d->vs_tf_denomination,2),1,0,'R');
					if($d->vs_gctype=='1')
					{
						$gctype = "Regular";
					}
					elseif($d->vs_gctype=='2')
					{
						$gctype="Promo";
					}
					elseif($d->vs_gctype=='3')
					{
						$gctype = "Special External";
					}
					$this->Cell(27,5,$gctype,1,0,'L');
					if(strlen($d->customer)>22)
					{
						$customername = substr($d->customer, 0, 22);
					}
					else 
					{
						$customername = $d->customer;
					}
					$this->Cell(40,5,ucwords(strtolower(utf8_decode(html_entity_decode($customername)))),1,0,'L');
					if($d->vs_tf_used=='*' && $d->vs_reverifydate=="")
					{
						$gcstatus = 'Redeemed';
					}
					$this->Cell(20,5,$gcstatus,1,0,'L');
					if($d->vs_reverifydate=="")
					{
						$balance = $d->vs_tf_balance;
					}
					else 
					{
						$balance = $d->vs_tf_denomination; 
					}
					$this->Cell(24,5,number_format($balance,2),1,0,'L');
					$this->Cell(24,5,$d->vs_date,1,0,'L');
					$this->Ln();
				}
			}
			else 
			{
				$this->Ln();
				$this->Cell(0, 8, 'Empty Result.', 0, 0, "C");	

			}

			if($d1==$d2)
			{
				$table = 'store_verification';
				$select = "store_verification.vs_barcode,
				    CONCAT(customers.cus_fname,' ',customers.cus_lname) as customer,
				    CONCAT(users.firstname,' ',users.lastname) as verby,
				    store_verification.vs_tf_denomination,
				    store_verification.vs_tf_used,
				    store_verification.vs_gctype,
				    store_verification.vs_date,
				    store_verification.vs_reverifydate,
				    store_verification.vs_tf_balance";
				$where = "DATE_FORMAT(store_verification.vs_reverifydate,'%Y-%m-%d') = '".$d1."' 
					AND 
						store_verification.vs_store='".$storeid."'";
				$join = 'LEFT JOIN
						customers
					ON
						customers.cus_id = store_verification.vs_cn
					LEFT JOIN
						users
					ON
						users.user_id = store_verification.vs_by';
				$limit = '';
				$datare = getAllData($link,$table,$select,$where,$join,$limit);
			}
			else
			{
				$table = 'store_verification';
				$select = "store_verification.vs_barcode,
				    CONCAT(customers.cus_fname,' ',customers.cus_lname) as customer,
				    CONCAT(users.firstname,' ',users.lastname) as verby,
				    store_verification.vs_tf_denomination,
				    store_verification.vs_tf_used,
				    store_verification.vs_gctype,
				    store_verification.vs_date,
				    store_verification.vs_reverifydate,
				    store_verification.vs_tf_balance";
				$where = "DATE_FORMAT(store_verification.vs_reverifydate,'%Y-%m-%d') >= '".$d1."'
					AND
						DATE_FORMAT(store_verification.vs_reverifydate,'%Y-%m-%d') <='".$d2."'
					AND
						store_verification.vs_store='".$storeid."'";
				$join = 'LEFT JOIN
						customers
					ON
						customers.cus_id = store_verification.vs_cn
					LEFT JOIN
						users
					ON
						users.user_id = store_verification.vs_by';
				$limit = '';
				$datare = getAllData($link,$table,$select,$where,$join,$limit);
			}


			if(count($datare) > 0)
			{
				$this->Ln();
				$this->Cell(0, 8, 'Reverified GC', 0, 0, "L");
				$this->Ln();
				$this->SetFont("Arial", "B", 9);
				$this->Cell(1,5,'',0,0,'R');
				$this->Cell(26,5,'Barcode #',1,0,'L');
				$this->Cell(24,5,'Denomination',1,0,'L');
				$this->Cell(27,5,'GC Type',1,0,'L');
				$this->Cell(40,5,'Customer',1,0,'L');
				$this->Cell(20,5,'Status',1,0,'L');
				$this->Cell(24,5,'Balance',1,0,'L');
				$this->Cell(24,5,'Date',1,0,'L');
				$this->Ln();				
				foreach ($datare as $d) 
				{
					$balance = "";
					$gctype="";
					$gcstatus = "";
					$customername = "";
					$this->Cell(1,5,'',0,0,'R');
					$this->Cell(26,5,$d->vs_barcode,1,0,'L');
					$this->Cell(24,5,number_format($d->vs_tf_denomination,2),1,0,'R');
					if($d->vs_gctype=='1')
					{
						$gctype = "Regular";
					}
					elseif($d->vs_gctype=='2')
					{
						$gctype="Promo";
					}
					elseif($d->vs_gctype=='3')
					{
						$gctype = "Special External";
					}
					$this->Cell(27,5,$gctype,1,0,'L');
					if(strlen($d->customer)>22)
					{
						$customername = substr($d->customer, 0, 22);
					}
					else 
					{
						$customername = $d->customer;
					}
					$this->Cell(40,5,ucwords(strtolower(utf8_decode(html_entity_decode($customername)))),1,0,'L');
					if($d->vs_tf_used=='*')
					{
						$gcstatus = 'Redeemed';
					}
					$this->Cell(20,5,$gcstatus,1,0,'L');
					$this->Cell(24,5,number_format($d->vs_tf_balance,2),1,0,'L');
					$this->Cell(24,5,$d->vs_date,1,0,'L');
					$this->Ln();
				}
			}
		}

		function signaturesVerification()
		{
			$this->Ln(12);
			$this->SetFont("Arial","", 10);
			$this->Cell(50,5,'',0,0,'L');
			$this->Cell(60,5,'',0,0,'L');
			$this->Cell(70,5,'Checked by:',0,0,'L');
			$this->Ln(8);
			$this->Cell(18,5,'',0,0,'R');
			$this->SetFont("Arial","B", 10);
			$this->Cell(50,5,'',0,0,'C');
			$this->Cell(60,5,'',0,0,'C');
			$this->Cell(50,5,'',0,0,'C');
			$this->Ln(1);
			$this->Cell(18,5,'',0,0,'R');
			$this->SetFont("Arial","", 10);
			$this->Cell(50,5,'',0,0,'C');
			$this->Cell(60,5,'',0,0,'C');
			$this->Cell(50,5,'_________________________',0,0,'C');
			$this->Ln();
			$this->Cell(18,5,'',0,0,'R');
			$this->SetFont("Arial", "", 7);
			$this->Cell(50,5,'',0,0,'C');
			$this->Cell(60,5,'',0,0,'C');
			$this->Cell(50,5,'( Signature over Printed name )',0,0,'C');		
		}

		function subheaderSalesReport($todays_date)
		{
			$this->SetFont("Arial", "B", 10);
			$this->Cell(28,5,'Generated By:',0,0,'R');
			$this->SetFont("Arial", "", 10);
			$this->Cell(86,5,ucwords($_SESSION['gc_fullname']),0,0,'L');
			$this->SetFont("Arial", "B", 10);
			$this->Cell(40,5,'Date Printed:',0,0,'R');
			$this->SetFont("Arial", "", 10);
			$this->Cell(50,5,_dateFormat($todays_date),0,0,'L');
			$this->Ln(10);
		}

		function showData($link,$gc)
		{
			if(count($gc)===0)
			{
				$this->Cell(0, 6,"Empty Result.", 0, 0, "C");

			}
			else
			{
				//var_dump($gc);
				foreach ($gc as $g) 
				{
					$this->Cell(10,5,"",0,0,'R');
					$this->Cell(28,5,"Transaction #","BT",0,'R');
					$this->Cell(28,5,$g->trans_number,"BT",0,'L');
					$this->Cell(85,5,"Date:","BT",0,'R');
					$this->Cell(40,5,_dateFormat($g->trans_datetime),"BT",0,'L');
					$this->Ln(8);


					$select = "transaction_sales.sales_barcode,
	    				denomination.denomination";
					$join = "INNER JOIN
							denomination
						ON
							denomination.denom_id = transaction_sales.sales_denomination";
					$where = "transaction_sales.sales_transaction_id ='".$g->trans_sid."'";
					$limit = "";

					$sales = getAllData($link,'transaction_sales',$select,$where,$join,$limit);
					asort($sales);
					//var_dump($sales);
					$line= 0;				
					$lineh = count($sales) / 3;

					$lineh = ceil($lineh);
					//echo $lineh.'ceil<br />';
					$linecnt = 0;
					foreach ($sales as $s) 
					{
						if($line==0)
						{
							$this->Cell(22,5,"",0,0,'R');
						}

						if($line <= 3)
						{
							$this->Cell(30,5,$s->sales_barcode,0,0,'R');
							$this->Cell(20,5,number_format($s->denomination,2),0,0,'R');						
						}

						$line++;
						
						
						if($line==3)
						{
							$linecnt++;
							//echo $linecnt.'<br>';
							$line = 0;
							if($linecnt=== $lineh)
							{
								echo 'sulod';
								break;
							}
							$this->Ln();						
						}
					}

					$this->Ln(12);
				}
			}
		}


		function subheaderTransferReleasing($data)
		{
			$this->Ln();
			$this->SetFont("Arial", "B", 10);
			$this->Cell(28,5,'GC Rel. No.: ',0,0,'R');
			$this->SetFont("Arial", "", 10);
			$this->Cell(86,5,sprintf("%03d",$data->tr_serverelnum),0,0,'L');
			$this->SetFont("Arial", "B", 10);
			$this->Cell(40,5,'Date Released:',0,0,'R');
			$this->SetFont("Arial", "", 10);
			$this->Cell(50,5,_dateFormat($data->tr_servedate),0,0,'L');
			$this->Ln();
			$this->SetFont("Arial", "B", 10);
			$this->Cell(28,5,'GCTRN: ',0,0,'R');
			$this->SetFont("Arial", "", 10);
			$this->Cell(86,5,sprintf("%03d",$data->tr_serverelnum),0,0,'L');
			$this->SetFont("Arial", "B", 10);
			$this->Cell(40,5,'Date Requested:',0,0,'R');
			$this->SetFont("Arial", "", 10);
			$this->Cell(50,5,_dateFormat($data->t_reqdatereq),0,0,'L');
			$this->Ln();
			$this->SetFont("Arial", "B", 10);
			$this->Cell(28,5,'Requested By:',0,0,'R');
			$this->SetFont("Arial", "", 10);
			$this->Cell(86,5,ucwords($data->storereqby),0,0,'L');
			$this->Ln(8);
		}

		function transferItems($denomgroup,$id,$link)
		{
			$this->SetFont("Arial", "", 10);

			foreach ($denomgroup as $d) 
			{
				$x=1;	
				$this->Cell(190,8,'Denomination: '.number_format($d->denomination,2),1,0,'L');
				$this->Ln(8);
				$gcs = getReleasedBarcodeByDenom($link,$id,$d->denom_id);			

				foreach ($gcs as $g) 
				{
					if($x<=5)
					{
						$this->Cell(40,	8,$g->trs_barcode,0,0,'L');
						$x++;
					}
					else 
					{	
						$x=1;										
						$this->Ln(5);
						$this->Cell(40,	8,$g->trs_barcode,0,0,'L');	
						$x++;											
					}
				}
				$pcs = $d->cnt > 1 ? 'pcs' : 'pc';
				$this->Ln(8);
				$this->Cell(140,8,'No of GC:','T',0,true);
				$this->Cell(50,8,$d->cnt.' '.$pcs,'T',0);
				$this->Ln(9);
			}
		}

		function transferInfo($link,$data)
		{
			$this->SetFont("Arial","", 10);
			$this->Cell(50,5,'Total Denomination Amount:',0,0,'R');
			$this->SetFont("Arial","B", 10);
			$this->Cell(50,5,number_format($data->sum,2),0,0,'L');
			$this->Ln();
			$this->SetFont("Arial","", 10);
			$this->Cell(50,5,'Total Number of GC:',0,0,'R');
			$this->SetFont("Arial","B", 10);
			$this->Cell(50,5,$data->cnt,0,0,'L');
			$this->Ln();
			$this->SetFont("Arial","", 10);
			$this->Cell(50,5,'Releasing Type:',0,0,'R');
			$this->SetFont("Arial","B", 10);
			$this->Cell(50,5,ucwords($data->tr_serveStatus),0,0,'L');
			$this->Ln(14);			
		}

		function signaturesTransferReleasing($link)
		{
			$this->SetFont("Arial","", 10);
			$this->Cell(50,5,'Prepared by:',0,0,'L');
			$this->Cell(60,5,'',0,0,'L');
			$this->Cell(70,5,'Checked by:',0,0,'L');
			$this->Ln(8);
			$this->Cell(18,5,'',0,0,'R');
			$this->SetFont("Arial","B", 10);
			$this->Cell(50,5,ucwords($_SESSION['gc_fullname']),0,0,'C');
			$this->Cell(60,5,'',0,0,'C');
			$this->Cell(50,5,ucwords($_SESSION['gc_fullname']),0,0,'C');
			$this->Ln(1);
			$this->Cell(18,5,'',0,0,'R');
			$this->SetFont("Arial","", 10);
			$this->Cell(50,5,'_________________________',0,0,'C');
			$this->Cell(60,5,'',0,0,'C');
			$this->Cell(50,5,'_________________________',0,0,'C');
			$this->Ln();
			$this->Cell(18,5,'',0,0,'R');
			$this->SetFont("Arial", "", 7);
			$this->Cell(50,5,'( Signature over Printed name )',0,0,'C');
			$this->Cell(60,5,'',0,0,'C');
			$this->Cell(50,5,'( Signature over Printed name )',0,0,'C');		
		}

		function signatures()
		{
			$this->SetFont("Arial","", 9);
			$this->Cell(50,5,'Audited by:',0,0,'L');
			$this->Cell(60,5,'',0,0,'L');
			$this->Cell(70,5,'Confirmed By:',0,0,'L');
			$this->Ln(12);
			$this->Cell(4,5,'',0,0,'R');
			$this->SetFont("Arial","B", 9);
			$this->Cell(50,5,'LUDIVIRA L. ABREU',0,0,'C');
			$this->Cell(10,5,'',0,0,'C');
			$this->Cell(55,5,'TINING PIZARRAZ',0,0,'C');
			$this->Cell(10,5,'',0,0,'C');
			$this->Cell(55,5,'NINA BONGCAC',0,0,'C');
			$this->Ln(4);
			$this->Cell(4,5,'',0,0,'R');
			$this->SetFont("Arial", "", 9);
			$this->Cell(50,5,'IAD - Staff',0,0,'C');
			$this->Cell(10,5,'',0,0,'C');
			$this->Cell(55,5,'CS Staff',0,0,'C');
			$this->Cell(10,5,'',0,0,'C');	
			$this->Cell(55,5,'CS Staff',0,0,'C');
			$this->Ln(10);
			$this->SetFont("Arial","", 9);
			$this->Cell(90,5,':',0,0,'L');
			$this->Cell(60,5,'Noted by:',0,0,'L');
			$this->Ln(12);
			$this->SetFont("Arial","B", 9);
			$this->Cell(97,5,'IGLESERIA SALAMAT',0,0,'C');
			$this->Cell(97,5,'FLOREME PORLARES, CPA',0,0,'C');
			$this->Ln(4);
			$this->SetFont("Arial", "", 9);
			$this->Cell(97,5,'ASC - Accounting Supervisor',0,0,'C');
			$this->Cell(97,5,'Accounting - ASC Jr. Supervisor',0,0,'C');
			$this->Ln(12);
			$this->SetFont("Arial","B", 9);
			$this->Cell(97,5,'IMEE Y. LACEA',0,0,'C');
			$this->Cell(97,5,'NENE B. MIRO',0,0,'C');
			$this->Ln(4);
			$this->SetFont("Arial", "", 9);
			$this->Cell(97,5,'ASC - IAD Jr. Supervisor',0,0,'C');
			$this->Cell(97,5,'AGC - IAD Head',0,0,'C');
		}

		// End store report

		function detailspromo($link,$denomgroup,$relid)
		{
			$this->SetFont("Arial", "", 10);
			foreach ($denomgroup as $d) 
			{
				$x=1;	
				$this->Cell(190,8,'Denomination: '.number_format($d->denomination,2),1,0,'L');
				$this->Ln(8);
				$gcs = getDenomReleasingReportByIdPromo($link,$relid,$d->denom_id);	
				foreach ($gcs as $g) 
				{
					if($x<=5)
					{
						$this->Cell(40,	8,$g->prreltoi_barcode,0,0,'L');
						$x++;
					}
					else 
					{	
						$x=1;										
						$this->Ln(5);
						$this->Cell(40,	8,$g->prreltoi_barcode,0,0,'L');	
						$x++;											
					}
				}
				$pcs = $d->cnt > 1 ? 'pcs' : 'pc';
				$this->Ln(8);
				$this->Cell(140,6,'No of GC:','TB',0,true);
				$this->Cell(50,6,$d->cnt.' '.$pcs,'TB',0);
				$this->Ln(9);
			}
		}

		function detailsIns($link,$denoms,$id)
		{
			$this->SetFont("Arial", "", 10);
			foreach ($denoms as $d) 
			{
				$x=1;	
				$this->Cell(190,8,'Denomination: '.number_format($d->denomination,2),1,0,'L');
				$this->Ln(8);
				$gcs = getDenomReleasingReportByIdIns($link,$id,$d->denom_id);	
				foreach ($gcs as $g) 
				{
					if($x<=5)
					{
						$this->Cell(40,	8,$g->instituttritems_barcode,0,0,'L');
						$x++;
					}
					else 
					{	
						$x=1;										
						$this->Ln(5);
						$this->Cell(40,	8,$g->instituttritems_barcode,0,0,'L');	
						$x++;											
					}
				}
				$pcs = $d->cnt > 1 ? 'pcs' : 'pc';
				$this->Ln(8);
				$this->Cell(140,6,'No of GC:','TB',0,true);
				$this->Cell(50,6,$d->cnt.' '.$pcs,'TB',0);
				$this->Ln(9);
			}
		}

		function eodCustomer($link,$data)
		{
			$total = 0;
			$items = 0;
			foreach ($data as $d) 
			{
				$this->SetFont("Arial", "", 10);
				$this->Cell(28,5,'Customer: ',0,0,'R');
				$this->SetFont("Arial","B", 10);
				$this->Cell(86,5,ucwords($d->ins_name),0,0,'L');
				$this->SetFont("Arial", "", 10);
				$this->Cell(40,5,'Rel #:',0,0,'R');
				$this->SetFont("Arial","B", 10);
				$this->Cell(50,5,sprintf("%03d",$d->institutr_trnum),0,0,'L');
				$this->Ln(6);


				$table = 'institut_transactions_items';
				$select = 'institut_transactions_items.instituttritems_barcode,
					denomination.denomination';
				$where = "instituttritems_trid='".$d->institutr_id."'";
				$join = 'LEFT JOIN
						gc
					ON
						gc.barcode_no = institut_transactions_items.instituttritems_barcode
					LEFT JOIN
						denomination
					ON
						denomination.denom_id = gc.denom_id';
				$limit = '';

				$gcs = getAllData($link,$table,$select,$where,$join,$limit);
				$this->Cell(10,5,'',0,0,'L');
				$this->Cell(44,5,'Barcode',1,0,'C');
				$this->Cell(44,5,'Denomination',1,0,'C');
				$this->Cell(44,5,'Barcode',1,0,'C');
				$this->Cell(44,5,'Denomination',1,0,'C');
				$this->Ln();
				$td = 0;

				$extra = false;
				$cnt = count($gcs);

				if($cnt%2!=0)
				{
					$div = floor($cnt / 2) + 1;
					$extra = true;
				}

				$loop = 0;
				$stotal = 0;
				$items += count($gcs);
				foreach ($gcs as $gc) 
				{
					if($td==0)
					{
						$this->Cell(10,5,'',0,0,'L');
					}

					$this->Cell(44,5,$gc->instituttritems_barcode,1,0,'C');
					$this->Cell(44,5,number_format($gc->denomination,2),1,0,'C');
					$td++;

					if($td==1)
					{
						$loop++;
						if($extra)
						{
							if($div==$loop)
							{
								$this->Cell(44,5,'',1,0,'C');
								$this->Cell(44,5,'',1,0,'C');
								$this->Ln();
							}
						}
					}			

					if($td==2)
					{
						$this->Ln();
						$td = 0;
					}
					$stotal += $gc->denomination;

				}
				$total += $stotal;
				$this->Ln(1);
				$this->Cell(10,5,'',0,0,'L');		
				$this->SetFont("Arial","", 10);		
				$this->Cell(28,5,'Payment Type:',0,0,'L');
				$this->SetFont("Arial","B", 10);
				$this->Cell(28,5,ucwords($d->institutr_paymenttype),0,0,'L');
				$this->SetFont("Arial","", 10);
				$this->Cell(98,5,'Sub-Total:',0,0,'R');
				$this->SetFont("Arial","B", 10);
				$this->Cell(30,5,number_format($stotal,2),0,0,'L');
				$this->Ln(10);				
			}
			$this->footerCashierAccountability($link,$total,$data,$items);


		}

		function footerCashierAccountability($link,$total,$data,$items)
		{
			$this->SetFont("Arial","", 10);
			$this->Cell(50,5,'GC Sold:',0,0,'R');
			$this->SetFont("Arial","B", 10);
			$this->Cell(50,5,$items,0,0,'L');
			$this->Ln();
			$this->SetFont("Arial","", 10);
			$this->Cell(50,5,'No. of Transactions:',0,0,'R');
			$this->SetFont("Arial","B", 10);
			$this->Cell(50,5,count($data),0,0,'L');
			$this->Ln();
			$this->SetFont("Arial","", 10);
			$this->Cell(50,5,'Total Sales:',0,0,'R');
			$this->SetFont("Arial","B", 10);
			$this->Cell(50,5,number_format($total,2),0,0,'L');
			$this->Ln(10);
			$this->SetFont("Arial","", 10);
			$this->Cell(125,5,'Prepared by:',0,0,'R');
			$this->Ln(8);
			$this->Cell(125,5,'',0,0,'R');
			$this->SetFont("Arial","B", 10);
			$this->Cell(60,5,ucwords($_SESSION['gc_fullname']),0,0,'C');
			$this->Ln(1);
			$this->Cell(125,5,'',0,0,'R');
			$this->SetFont("Arial","", 10);
			$this->Cell(60,5,'____________________________',0,0,'L');
			$this->Ln();
			$this->Cell(125,5,'',0,0,'R');
			$this->SetFont("Arial", "", 7);
			$this->Cell(60,5,'( Signature over Printed name )',0,0,'C');

		}

		function subheaderCashierAccountability($data)
		{
			$this->SetFont("Arial", "", 10);
			$this->Cell(28,5,'EOD No.: ',0,0,'R');
			$this->SetFont("Arial", "B", 10);
			$this->Cell(86,5,sprintf("%03d",$data->ieod_num),0,0,'L');
			$this->SetFont("Arial", "", 10);
			$this->Cell(40,5,'Date:',0,0,'R');
			$this->SetFont("Arial", "B", 10);
			$this->Cell(50,5,_dateFormat($data->ieod_date),0,0,'L');
			$this->Ln();
			$this->SetFont("Arial", "", 10);
			$this->Cell(154,5,'Time:',0,0,'R');
			$this->SetFont("Arial", "B", 10);
			$this->Cell(50,5,_timeFormat($data->ieod_date),0,0,'L');
			$this->Ln(12);		
		}

		function subheaderInst($id,$data)
		{
			$this->Ln();
			$this->SetFont("Arial", "", 10);
			$this->Cell(28,5,'GC Rel. No.: ',0,0,'R');
			$this->SetFont("Arial", "B", 10);
			$this->Cell(86,5,sprintf("%03d",$data->institutr_trnum),0,0,'L');
			$this->SetFont("Arial", "", 10);
			$this->Cell(40,5,'Date Released:',0,0,'R');
			$this->SetFont("Arial", "B", 10);
			$this->Cell(50,5,_dateFormat($data->institutr_date),0,0,'L');
			$this->Ln();
			$this->SetFont("Arial", "", 10);
			$this->Cell(28,5,'Customer: ',0,0,'R');
			$this->SetFont("Arial", "B", 10);
			$this->Cell(86,5,ucwords($data->ins_name),0,0,'L');
			$this->Ln(12);			
		}

		function subfooterpromo($data,$count)
		{
			$this->SetFont("Arial", "", 10);
			$this->Cell(30,	8,'Releasing Type:',0,0,'R');
			$this->Cell(60,	8,ucwords($data->prrelto_status),0,0,'L');
			$this->Ln(5);
			$this->Cell(30,	8,'Total No. of GC:',0,0,'R');
			$this->Cell(60,	8,$count->cnt.' pcs',0,0,'L');
			$this->Ln(5);
			$this->Cell(30,	8,'Total GC Amount:',0,0,'R');
			$this->Cell(60,	8,number_format($count->total,2),0,0,'L');
			$this->SetFont("Arial", "", 10);
			$this->Ln(8);
			$this->Cell(105,8,'Prepared by:',0,0,'L');
			$this->Cell(80,8,'Checked by:',0,0,'L');
			$this->Ln(8);
			$this->SetFont("Arial", "B", 10);
			$this->Cell(80,	8,ucwords($data->user),0,0,'C');
			$this->Cell(34,8,'',0,0,'C');
			$this->Cell(60,8,$data->prrelto_checkedby,0,0,'C');
			$this->Ln(4);
			$this->SetFont("Arial", "", 10);
			$this->Cell(18,	1,'',0,0,'R');
			$this->Cell(50,	1,'______________________________',0,0,'C');
			$this->Cell(36,	1,'',0,0,'C');
			$this->Cell(80,	1,'______________________________',0,0,'C');
			$this->Ln(5);
			$this->SetFont("Arial", "B", 7);
			$this->Cell(13,	1,'',0,0,'C');
			$this->Cell(60,	1,'(Signature over Printed name)',0,0,'C');
			$this->Cell(41,	1,'',0,0,'C');
			$this->Cell(60,	1,'(Signature over Printed name)',0,0,'C');
			$this->Ln(8);
			$this->SetFont("Arial", "", 10);
			$this->Cell(105,8,'',0,0,'L');
			$this->Cell(80,8,'Approved by:',0,0,'L');
			$this->Ln(8);
			$this->SetFont("Arial", "B", 10);
			$this->Cell(80,	8,'',0,0,'C');
			$this->Cell(34,8,'',0,0,'C');
			$this->Cell(60,8,$data->prrelto_approvedby,0,0,'C');
			$this->Ln(4);
			$this->SetFont("Arial", "", 10);
			$this->Cell(18,	1,'',0,0,'R');
			$this->Cell(50,	1,'',0,0,'C');
			$this->Cell(36,	1,'',0,0,'C');
			$this->Cell(80,	1,'______________________________',0,0,'C');
			$this->Ln(5);
			$this->SetFont("Arial", "B", 7);
			$this->Cell(13,	1,'',0,0,'C');
			$this->Cell(60,	1,'',0,0,'C');
			$this->Cell(41,	1,'',0,0,'C');
			$this->Cell(60,	1,'(Signature over Printed name)',0,0,'C');
		}

		function subfooterIns($data,$count)
		{
			$this->SetFont("Arial", "", 10);
			$this->Cell(30,	8,'Total No. of GC:',0,0,'R');
			$pcs = 
			$this->Cell(60,	8,$count->cnt.' pcs',0,0,'L');
			$this->Ln(5);
			$this->Cell(30,	8,'Total GC Amount:',0,0,'R');
			$this->Cell(60,	8,$count->total,0,0,'L');
			$this->SetFont("Arial", "", 10);
			$this->Ln(8);
			$this->Cell(105,8,'Received by:',0,0,'L');
			$this->Cell(80,8,'Released by:',0,0,'L');
			$this->Ln(8);
			$this->SetFont("Arial", "B", 10);
			$this->Cell(80,	8,ucwords($data->institutr_receivedby),0,0,'C');
			$this->Cell(34,8,'',0,0,'C');
			$this->Cell(60,8,ucwords($data->relby),0,0,'C');
			$this->Ln(4);
			$this->SetFont("Arial", "", 10);
			$this->Cell(18,	1,'',0,0,'R');
			$this->Cell(50,	1,'______________________________',0,0,'C');
			$this->Cell(36,	1,'',0,0,'C');
			$this->Cell(80,	1,'______________________________',0,0,'C');
			$this->Ln(5);
			$this->SetFont("Arial", "B", 7);
			$this->Cell(13,	1,'',0,0,'C');
			$this->Cell(60,	1,'(Signature over Printed name)',0,0,'C');
			$this->Cell(41,	1,'',0,0,'C');
			$this->Cell(60,	1,'(Signature over Printed name)',0,0,'C');
			$this->Ln(8);
		}
	
	}

